### ISSUE TITLE
Add 0 as a Frequency Option for Field Configs

### ISSUE THREAD

**Issue by jonofoz** [Werewoof/songscaffolder#6]
Currently, there's no way to disable a specific entry in a field's config without deleting the entry. The best that can be done currently is to place it on the lowest frequency, `1`, but that simply moves it to being "rare".

- [x] Add that 0 to them entries

**Comment by Werewoof** [comment]
This issue has been merged into master.

**Comment by jonofoz** [comment]
This issue has been merged into master.
